### ISSUE TITLE
Accessing any program fails

### ISSUE THREAD

**Issue by zkrx** [goggle/plugin.video.rtsplaytv#5]
On alarm, I have the following failure with any program:
```
2020-06-17 22:08:04.149 T:1516237072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.rtsplaytv/addon.py", line 23, in <module>
                                                rtsplaytv.run()
                                              File "/home/user/.kodi/addons/plugin.video.rtsplaytv/resources/lib/rtsplaytv.py", line 135, in run
                                                RTSPlayTV().build_show_menu(name, page_hash=page_hash)
                                              File "/home/user/.kodi/addons/script.module.srgssr/lib/srgssr.py", line 603, in build_show_menu
                                                json_response = json.loads(self.open_url(json_url))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-06-17 22:08:04.310 T:1565520144   ERROR: GetDirectory - Error getting plugin://plugin.video.rtsplaytv/?mode=20&name=511875
2020-06-17 22:08:04.312 T:1903735824   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.rtsplaytv/?mode=20&name=511875) failed
```

`Linux 5.4.45-1-ARCH #1 SMP PREEMPT Sun Jun 14 20:09:21 UTC 2020 armv7l GNU/Linux`

```
2020-06-17 22:05:12.243 T:1903735824  NOTICE: Starting Kodi (18.7 Git:20200602-nogitfound). Platform: Linux ARM 32-bit
2020-06-17 22:05:12.243 T:1903735824  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2020-06-17 22:05:12.243 T:1903735824  NOTICE: Kodi compiled 2020-06-02 by GCC 9.3.0 for Linux ARM 32-bit version 5.6.11 (329227)
2020-06-17 22:05:12.244 T:1903735824  NOTICE: Running on Arch Linux ARM 0.0, kernel: Linux ARM 32-bit version 5.4.45-1-ARCH
2020-06-17 22:05:12.256 T:1903735824  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2020-06-17 22:05:12.256 T:1903735824  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
2020-06-17 22:05:12.256 T:1903735824  NOTICE: ARM Features: Neon enabled
```

`2020-06-17 22:05:12.735 T:1903735824  NOTICE: ADDON: plugin.video.rtsplaytv v1.6.0 installed`

Rings any bell?

**Comment by joachimBurket** [comment]
That's because SRG SSR updated their API (see https://github.com/goggle/script.module.srgssr/issues/3). 
A pull request supporting the APIv3 is done on `script.module.srgssr` repository, but before the release is updated on Kodi repo, the `script.module.srgssr` repository has to be cloned on the addons folder to replace the old one. The line 93 must also be modified `lib/srgssr.py` for the RTS support:
```python
if bu == 'srf' or 'rts':
    self.apiv3_url = self.host_url + '/play/v3/api/%s/production/' % bu
```

**Comment by goggle** [comment]
Support for the APIv3 has been added, but the plugin will only continue to be maintained for Kodi `matrix`.
It should all work fine on the `master` branch or in the prerelease version `1.9.99` and will hopefully soon be in the official Kodi repository (https://github.com/xbmc/repo-plugins/pull/3985).
