### ISSUE TITLE
Loading YouTube channels fails

### ISSUE THREAD

**Issue by goggle** [goggle/plugin.video.rtsplaytv#6]
Debug log:
```
2022-04-23 03:47:59.499 T:6261    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeDecodeError'>
                                                   Error Contents: 'ascii' codec can't decode byte 0xc3 in position 55: ordinal not in range(128)
                                                   Traceback (most recent call last):
                                                     File "/home/alex/.kodi/addons/plugin.video.rtsplaytv/addon.py", line 23, in <module>
                                                       rtsplaytv.run()
                                                     File "/home/alex/.kodi/addons/plugin.video.rtsplaytv/resources/lib/rtsplaytv.py", line 144, in run
                                                       RTSPlayTV().build_youtube_channel_overview_menu(33)
                                                     File "/home/alex/.kodi/addons/script.module.srgssr/lib/srgssr.py", line 1399, in build_youtube_channel_overview_menu
                                                       channel_ids = self.get_youtube_channel_ids()
                                                     File "/home/alex/.kodi/addons/script.module.srgssr/lib/srgssr.py", line 1363, in get_youtube_channel_ids
                                                       channel_ids = self._read_youtube_channels(
                                                     File "/home/alex/.kodi/addons/script.module.srgssr/lib/srgssr.py", line 1349, in _read_youtube_channels
                                                       ch_content = json.load(f)
                                                     File "/usr/lib/python3.9/json/__init__.py", line 293, in load
                                                       return loads(fp.read(),
                                                     File "/usr/lib/python3.9/encodings/ascii.py", line 26, in decode
                                                       return codecs.ascii_decode(input, self.errors)[0]
                                                   UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 55: ordinal not in range(128)
                                                   -->End of Python script error report<--
```

**Comment by claudep** [comment]
Modern JSON can now contain unencoded UTF-8 characters, so I guess it would be better to open files forcing the `utf-8` encoding. So in `_read_youtube_channels()` of `srgssr.py`, I would suggest:
```
with open(data_file, 'r', encoding='utf-8') as f:
      ch_content = json.load(f)
```

**Comment by goggle** [comment]
@claudep Thanks, that was indeed the issue.
